force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account__x/Account__x.object-meta.xml
<CustomObject>
    <externalDataSource>Source_Org</externalDataSource>
    <externalName>Account</externalName>
    <label>Account</label>
    <pluralLabel>Accounts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account__x/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <externalDeveloperName>Industry</externalDeveloperName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Not For Profit</fullName>
            </value>
            <value>
                <fullName>Recreation</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account__x/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <externalDeveloperName>Name</externalDeveloperName>
    <label>Account Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchToSyncExternalAccountRecord.cls
/*******************************************************************************
* Avenoir Technologies Pvt. Ltd. All rights reserved.
* Ticket Number: AVEBLOG111
--------------------------------------------------------------------------------
* Purpose/Methods: Return the required result.
* Class: BatchToSyncExternalAccountRecord.cls
--------------------------------------------------------------------------------
* Version History:
* VERSION     DEVELOPER NAME      DATE       DETAIL FEATURES
* 1.0         Shiv K Chaudhary    09/11/2024   Initial Development
* ****************************************************************************/
public with sharing class BatchToSyncExternalAccountRecord implements Database.Batchable<sObject> {
     /**
    * This method aims return the required result.
    * @param context
    * @return Database.QueryLocator
    */
    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator('SELECT Id, Name__c, Industry__c FROM Account__x');
    }

     /**
    * This method aims to process the Sync the Account Data
    * @param context
    * @param externalAccounts
    */
    public void execute(Database.BatchableContext context, List<Account__x> externalAccounts) {
        List<Account> accountsToUpsert = new List<Account>();
        for (Account__x externalAccount : externalAccounts) {
            // Map fields to target org’s Account object
            Account accountNew = new Account();
            accountNew.External_Id__c = externalAccount.Id;
            accountNew.Name = externalAccount.Name__c;
            accountsToUpsert.add(accountNew);
        }
        upsert accountsToUpsert Account.External_Id__c;
    }

    /**
    * This method aims to process show the results
    * @param context
    */
    public void finish(Database.BatchableContext context) {
        System.debug(System.label.ACCOUNT_SYNC_COMPLETED);
    }
}